#!bin/sh

# homebrew golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# python paths
export PATH=$PATH:/Users/jc/Library/Python/3.7/bin

# colors
alias ls='ls -G'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jcastillo/google-cloud-sdk/path.bash.inc' ]; then . '/Users/jcastillo/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jcastillo/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/jcastillo/google-cloud-sdk/completion.bash.inc'; fi

export HELM_HOME=$HOME/Documents/git/dotfiles/config/helm_plugins
export PATH=$PATH:~/.kube/plugins/jordanwilson230
export IMG_REGISTRY="us.gcr.io/rp-stage"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export HOMEBREW_GITHUB_API_TOKEN=0fd6d59eb5e6a462c2e80e3b44119a32098f5403

# OS
export OS_LOADED=MAC
