#!bin/sh

# homebrew golang
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# colors
alias ls='ls -G'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jc/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/jc/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jc/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/jc/Downloads/google-cloud-sdk/completion.bash.inc'; fi

# OS
export OS_LOADED=MAC
