#!bin/sh


export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH="$PATH:$GOPATH:$GOBIN"
export PATH="/usr/local/go/bin:$PATH"

# export PATH=$PATH:$HOME/Apps/GoLand-2017.3.2/bin
# export PATH=$PATH:$HOME/Apps/liquibase-3.4.2

export PATH=$PATH:$HOME/.local/bin

# homebrew
# export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
# eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# brew install gcc
# export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/isl@0.18/lib"
# export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include"
# export PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/opt/isl@0.18/lib/pkgconfig"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export USE_BAZEL_VERSION=0.26.1

source "/etc/profile.d/rvm.sh"

# OS
export OS_LOADED=LINUX

